name: Run nix build on repo.
run-name: ${{ gitea.actor }} builds all.
on: [push]

jobs:
  Build:
    runs-on: gitea-latest
    container:
      credentials:
        username: luca
        password: "${{ secrets.ACT_RUNNER_REGISTRY }}"
    steps:
      - uses: actions/checkout@v4
      - run: nix build
      - run: nix store sign -k /root/nix-store-key $(nix-store --query --deriver ./result)
      - run: nix copy --to 's3://nix-cache?profile=default&scheme=https&endpoint=s3.dcr.lu&region=europe-01' $(nix-store --query --deriver ./result)
