name: Run nix build on repo.
run-name: ${{ gitea.actor }} builds all.
on: [push]

jobs:
  Build:
    runs-on: gitea-latest
    container:
      credentials:
        username: luca
        password: "${{ secrets.ACT_RUNNER_REGISTRY }}"
    steps:
      - uses: actions/checkout@v6
      - run: |
          OUT="$(nix build --no-link --print-out-paths .#)"
          REFS="$(nix-store --query --references $OUT)"
          nix store sign --recursive --key-file /root/nix-store-key $OUT $REFS
          nix copy --to 's3://dcr-nix-cache?profile=garage&scheme=http&endpoint=garage.dcr.lu&region=europe01' $OUT $REFS
